# Generated by Django 2.1 on 2018-08-13 15:18

import datetime
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Insurers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='RiskEntries',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(default=datetime.date.today)),
                ('risk_data', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='RiskTypes',
            fields=[
                ('code', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('full_risk_name', models.CharField(max_length=100)),
                ('risk_metadata', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
        migrations.AddField(
            model_name='riskentries',
            name='code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='riskapp.RiskTypes'),
        ),
        migrations.AddField(
            model_name='riskentries',
            name='insurer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='riskapp.Insurers'),
        ),
        migrations.AlterUniqueTogether(
            name='riskentries',
            unique_together={('id', 'code')},
        ),
    ]
